env:
  browser: true
  es6: true
  node: true
  jest/globals: true
plugins:
  - "jest"
  - "svelte3"
extends:
  - "eslint:recommended"
  - "plugin:jest/recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
overrides: [{ files: ["**/*.svelte"], processor: "svelte3/svelte3" }]
