root: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2020
  sourceType: module
plugins:
  - "@typescript-eslint"
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - prettier/@typescript-eslint
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:node/recommended
  - plugin:import/typescript
rules:
  node/no-missing-import:
    ["error", { "tryExtensions": [".ts", ".js", ".json", ".node"] }]
  node/no-unsupported-features/es-syntax:
    ["error", { "version": ">=13.0.0", "ignores": [modules] }]
